# Generated by Django 3.0.9 on 2020-08-13 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('transaction_type', models.CharField(max_length=1)),
                ('num_shares', models.IntegerField()),
                ('trade_at', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Current stock price when order was made')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.Profile')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='stocks.Stock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
