# Generated by Django 3.0.9 on 2020-08-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_auto_20200813_1313"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="owner", new_name="trader",
        ),
    ]
