# Generated by Django 3.0.9 on 2020-08-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20200813_1235"),
    ]

    operations = [
        migrations.AlterModelOptions(name="user", options={},),
        migrations.AlterModelManagers(name="user", managers=[],),
        migrations.RemoveField(model_name="user", name="date_joined",),
        migrations.RemoveField(model_name="user", name="first_name",),
        migrations.RemoveField(model_name="user", name="is_active",),
        migrations.RemoveField(model_name="user", name="is_staff",),
        migrations.RemoveField(model_name="user", name="last_name",),
    ]
